# Use the official Kibana image from Docker Hub
FROM docker.elastic.co/kibana/kibana:8.15.1

# Set necessary environment variables
ENV ELASTICSEARCH_HOSTS=http://elasticsearch:9200

# Expose Kibana's default port
EXPOSE 5601

# Set the entry point for Kibana
ENTRYPOINT ["/bin/tini", "--", "/usr/local/bin/kibana-docker"]

# Start Kibana without any extra options
CMD []