# Dockerfile.fleet
FROM docker.elastic.co/beats/elastic-agent:8.15.1

# Set environment variables for Fleet Server
ENV FLEET_SERVER_ENABLE=1
ENV FLEET_SERVER_PORT=8220

# Expose the Fleet Server port
EXPOSE 8220

# Start Fleet Server
ENTRYPOINT ["/usr/local/bin/docker-entrypoint"]
CMD ["-e", "--fleet-server"]
