---
- name: Pull Git Repository, Build and Run Docker Containers for ELK Stack
  hosts: all
  become: yes
  vars:
    git_repo: 'https://github.com/CastanheiraOnCode/thesis.git'
    git_dest: '/home/joao-tese/repo'
    docker_compose_file: 'automation/docker-compose.yml'
    elastic_password: "elastic"  # Password for 'elastic' user

  tasks:
    - name: Ensure git is installed
      apt:
        name: git
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Docker Compose-v2 is installed
      apt:
        name: docker-compose-v2
        state: present
      when: ansible_os_family == "Debian"

    - name: Clone the Git repository
      git:
        repo: "{{ git_repo }}"
        dest: "{{ git_dest }}"
        version: main
      register: git_clone

    - name: Build and run Docker containers using Docker Compose
      command: docker compose -f "{{ git_dest }}/{{ docker_compose_file }}" up -d
      args:
        chdir: "{{ git_dest }}"

    - name: Wait for Elasticsearch to become available
      wait_for:
        port: 9200
        delay: 10
        timeout: 60

    - name: Create service account token for Kibana
      command: >
        curl -X POST "http://localhost:9200/_security/service/elastic/kibana/credential/token/default"
        -H "Content-Type: application/json"
        -u elastic:{{ elastic_password }}
      register: service_token_creation
      ignore_errors: yes

    - name: Extract service account token from output
      set_fact:
        kibana_service_token: "{{ service_token_creation.stdout | regex_search('token\":\"(.*?)\"', '\\1') }}"
      when: service_token_creation is succeeded

    - name: Debug the service token
      debug:
        msg: "Kibana service token: {{ kibana_service_token }}"

    - name: Replace the contents of docker-compose.yml with the template
      template:
        src: "automation/docker-compose.yml.j2"  # Ensure you have a template with the service token
        dest: "{{ git_dest }}/{{ docker_compose_file }}"
      vars:
        KIBANA_SERVICE_TOKEN: "{{ kibana_service_token }}"

    - name: Restart the Docker containers
      command: docker compose -f "{{ git_dest }}/{{ docker_compose_file }}" up -d
      args:
        chdir: "{{ git_dest }}"

    - name: Wait for Kibana to become available
      wait_for:
        port: 5601
        delay: 10
        timeout: 60

    # Other tasks for building and running Elastic Agent

    # Build and run Elastic Agent in standalone mode
    - name: Build Elastic Agent Docker image for standalone mode
      command: docker build -t {{ elastic_agent_image }} -f {{ git_dest }}/automation/docker/Dockerfile.elastic-agent {{ git_dest }}/automation/docker

    - name: Start Elastic Agent container in standalone mode
      command: >
        docker run -d --name elastic-agent
        --network automation_default
        -p 8221:8221
        {{ elastic_agent_image }}

    - name: Debug Elastic Agent logs (optional)
      command: docker logs elastic-agent
      register: agent_logs

    - name: Show Elastic Agent logs
      debug:
        msg: "{{ agent_logs.stdout }}"
