---
- name: Pull Git Repository, Build and Run Docker Containers for ELK Stack
  hosts: all
  become: yes
  vars:
    git_repo: 'https://github.com/CastanheiraOnCode/thesis.git'
    git_dest: '/home/joao-tese/repo'
    docker_compose_file: 'automation/docker-compose.yml'
    
  tasks:
    - name: Ensure git is installed
      apt:
        name: git
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Docker Compose is installed
      apt:
        name: docker-compose
        state: present
      when: ansible_os_family == "Debian"

    - name: Clone the Git repository
      git:
        repo: "{{ git_repo }}"
        dest: "{{ git_dest }}"
        version: main
      register: git_clone

    - name: Build and run Docker containers using Docker Compose
      command: docker compose -f "{{ git_dest }}/{{ docker_compose_file }}" up -d
      args:
        chdir: "{{ git_dest }}"

    - name: Wait for Kibana to become available
      wait_for:
        port: 5601
        delay: 10
        timeout: 60


    # Build and run Elastic Agent in standalone mode
    - name: Build Elastic Agent Docker image for standalone mode
      command: docker build -t {{ elastic_agent_image }} -f {{ git_dest }}/automation/docker/Dockerfile.elastic-agent {{ git_dest }}/automation/docker

    - name: Start Elastic Agent container in standalone mode
      command: >
        docker run -d --name elastic-agent
        --network automation_default
        -p 8221:8221
        {{ elastic_agent_image }}

    - name: Debug Elastic Agent logs (optional)
      command: docker logs elastic-agent
      register: agent_logs

    - name: Show Elastic Agent logs
      debug:
        msg: "{{ agent_logs.stdout }}"
