[package]
name = "traffic_classification"
version = "0.1.0"
edition = "2021"

[dependencies]
elasticsearch = "8.15.0-alpha.1"
serde = "~1"
serde_json = "~1"
tokio = { version = "*", features = ["full"] }
url = "2.5.2"
