version: '3.8'

services:
  elasticsearch:
    build:
      context: ./docker
      dockerfile: Dockerfile.elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true  # Enable security for API keys
      - xpack.security.authc.api_key.enabled=true  # Enable API key auth
      - ELASTIC_PASSWORD=elastic  # Set a password for the 'elastic' user
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    build:
      context: ./docker
      dockerfile: Dockerfile.kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic  # Using the elastic user initially to set up
      - ELASTICSEARCH_PASSWORD=elastic
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata:
