version: '3.8'

services:
  elasticsearch:
    build:
      context: ./docker
      dockerfile: Dockerfile.elasticsearch
    environment:
      ELASTIC_PASSWORD: elastic  # Set the password for the elastic user
      discovery.type: single-node
      xpack.security.enabled: "true"  # Enable security
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    build:
      context: ./docker
      dockerfile: Dockerfile.kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      KIBANA_USERNAME: elastic  # Set the username for Kibana
      KIBANA_PASSWORD: elastic  # Set the password for Kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata:
