version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    container_name: es01
    environment:
      - ELASTIC_PASSWORD=elastico
      - discovery.type=single-node
    networks:
      - elastic
    ports:
      - "9200:9200"
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastico
      - SERVER_NAME=kibana
    networks:
      - elastic
    ports:
      - "5601:5601"

networks:
  elastic:
