version: '3.8'

services:
  elasticsearch:
    build:
      context: ./docker
      dockerfile: Dockerfile.elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true  # Enable security features
      - ELASTIC_PASSWORD=kibana # Set the password for the 'elastic' user
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    build:
      context: ./docker
      dockerfile: Dockerfile.kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=admin  # Use the new user for Kibana
      - ELASTICSEARCH_PASSWORD=kibana  # Password for the new user
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata:
